version: '3'
services:
  flask-service:
      build: flask-service
      volumes:
        - ./flask-service:/usr/src/app
      ports:
        - 5001:80

  apache-service:
      image: php:apache
      volumes:
        - ./apache-service:/var/www/html
      ports:
        - 5000:80
      depends_on:
        - flask-service

  nginx-service:
    image: nginx:alpine
    ports:
        - 80:80
    volumes:
        - ./nginx-service:/code
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - phpfpm

  phpfpm:
    image: php:fpm
    ports:
        - 9000:9000
    volumes:
        - ./nginx-service:/code

